### ISSUE TITLE
Fun issue for Drew?

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/quickb#1]
@wrathematics you may like this one:

> f <- map("foo", TRUE)
> length(f)
[1] 0
> match_entries(f, "bar")
[1] TRUE

I have no idea what's going on, since non-R-involving versions of the same operations work perfectly (see `test.cpp`. Pointer referencing problem?

**Comment by Ironholds** [comment]
From extracting values from newly-created logical tries it looks like it's simply not inserting any key/value pair where the value is TRUE. Wat. Unless TRUE is..also the NA_LOGICAL value, which seems off.

**Comment by wrathematics** [comment]
I haven't had a chance to look yet, but if you're using bool and letting Rcpp cast things, then `TRUE` is the same as `NA_LOGICAL`, because the latter is `INT_MIN` and anything other than 0 is cast to `true` as a bool (and `INT_MIN != 0` ;)). This actually came up in triebeard, but I can't find it; probably somewhere in `str()`.

**Comment by Ironholds** [comment]
Oh for gods sakes. So when I'm doing the initial check of 'if it's NA,
don't insert it'...so I should do NA-checking R-side. Cool!

**Comment by Ironholds** [comment]
Finally fixed it. I need to write down the answer. Good fucking god.
